#!/bin/bash
echo "============================================"
echo " Notion Workspace Codex Plugin - Setup"
echo "============================================"
echo ""
echo "Step 1: Install Node.js dependencies..."
cd "$(dirname "$0")/mcp-server"
npm install
echo ""
echo "Step 2: Configure your Notion API Key"
echo ""
echo "  1. Go to https://www.notion.so/my-integrations"
echo "  2. Create a new Internal Integration"
echo "  3. Copy the \"Internal Integration Secret\""
echo "  4. Add to your shell profile:"
echo ""
echo "     export NOTION_API_KEY=\"your_secret_key_here\""
echo ""
echo "Step 3: Restart Codex and use the plugin"
echo ""
echo "Done!"
